export const TOEFL_TOPICS: { value: string; label: string; emoji: string }[] = [
  { value: 'biology',       label: '생물학',    emoji: '🧬' },
  { value: 'chemistry',     label: '화학',      emoji: '⚗️' },
  { value: 'physics',       label: '물리학',    emoji: '⚛️' },
  { value: 'astronomy',     label: '천문학',    emoji: '🔭' },
  { value: 'geology',       label: '지질학',    emoji: '🪨' },
  { value: 'ecology',       label: '생태학',    emoji: '🌿' },
  { value: 'history_us',    label: '미국사',    emoji: '🗽' },
  { value: 'history_world', label: '세계사',    emoji: '🌍' },
  { value: 'anthropology',  label: '인류학',    emoji: '🏺' },
  { value: 'psychology',    label: '심리학',    emoji: '🧠' },
  { value: 'sociology',     label: '사회학',    emoji: '👥' },
  { value: 'economics',     label: '경제학',    emoji: '📊' },
  { value: 'art_music',     label: '예술/음악', emoji: '🎨' },
  { value: 'literature',    label: '문학',      emoji: '📚' },
  { value: 'architecture',  label: '건축학',    emoji: '🏛️' },
  { value: 'environmental', label: '환경과학',  emoji: '🌊' },
  { value: 'linguistics',        label: '언어학',    emoji: '🗣️' },
  { value: 'philosophy',         label: '철학',      emoji: '🧭' },
  { value: 'political_science',  label: '정치학',    emoji: '🏛️' },
  { value: 'medicine',           label: '의학',      emoji: '🏥' },
  { value: 'technology',         label: '기술/공학', emoji: '⚙️' },
  { value: 'general',            label: '일반',      emoji: '📝' },
]
